name: Publish

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Tests
        run: pnpm test-ci

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@v1.9.18
        with:
          coverage-summary-path: ./coverage/coverage-final.json

      - name: Bump package version
        id: bumping-version
        uses: jpb06/bump-package@v2.5.12
        with:
          major-keywords: BREAKING CHANGE
          minor-keywords: feat,minor
          patch-keywords: fix,chore
          should-default-to-patch: true

      - name: Building package
        run: pnpm build

      - name: Publish package
        if: steps.bumping-version.outputs.bump-performed == 'true'
        run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
